# -*- coding: utf-8 -*-
"""codigo_para_cargar_db_1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8bUJ5YV1L4VFEieWs-XMLQ4O8xJZMze
"""

!pip install tabulate

# -*- coding: utf-8 -*-
"""codigo_para_cargar_db.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8bUJ5YV1L4VFEieWs-XMLQ4O8xJZMze
"""

import pandas as pd
from tabulate import tabulate

# Cargar los CSV de los tres datasets
df_girls = pd.read_csv("/content/GirlsGenerations.csv", encoding="latin1", delimiter=";")
df_shinee = pd.read_csv("/content/SHINee cvs.csv", encoding="latin1", delimiter=";")
df_superjunior = pd.read_csv("/content/SuperJunior.csv", encoding="latin1", delimiter=";")

# Mostrar las primeras filas de cada dataset en formato tabla
print("GirlsGenerations DataFrame:")
print(tabulate(df_girls.head(), headers='keys', tablefmt='grid', showindex=False))

print("\nSHINee DataFrame:")
print(tabulate(df_shinee.head(), headers='keys', tablefmt='grid', showindex=False))

print("\nSuperJunior DataFrame:")
print(tabulate(df_superjunior.head(), headers='keys', tablefmt='grid', showindex=False))