# -*- coding: utf-8 -*-
"""codigo_para_cargar_db.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8bUJ5YV1L4VFEieWs-XMLQ4O8xJZMze
"""

import pandas as pd

# Cargar los CSV de los tres datasets
df_girls = pd.read_csv("/content/GirlsGenerations.csv", encoding="latin1", delimiter=";")
df_shinee = pd.read_csv("/content/SHINee cvs.csv", encoding="latin1", delimiter=";")
df_superjunior = pd.read_csv("/content/SuperJunior.csv", encoding="latin1", delimiter=";")

# Mostrar las primeras filas de cada dataset para verificar
print("GirlsGenerations DataFrame:")
print(df_girls.head())

print("\nSHINee DataFrame:")
print(df_shinee.head())

print("\nSuperJunior DataFrame:")
print(df_superjunior.head())