# -*- coding: utf-8 -*-
"""codigo_para_cargar_db_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X3Vlaao-_oRpi5tcEyjbQf7Q74kOqAv_
"""

import pandas as pd
datos = pd.read_csv ("/content/drive/MyDrive/conciertos_database_limpia.csv", encoding = "latin1", delimiter = ";")
datos