# -*- coding: utf-8 -*-
"""codigo_para_cargar_db_1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8bUJ5YV1L4VFEieWs-XMLQ4O8xJZMze
"""

from google.colab import files
uploaded = files.upload()


!ls

import pandas as pd

df = pd.read_csv("GirlsGenerations.csv", encoding="latin1", delimiter=";")
df.head()
import pandas as pd

df_girls = pd.read_csv("GirlsGenerations.csv", encoding="latin1", delimiter=";")
df_shinee = pd.read_csv("SHINee cvs.csv", encoding="latin1", delimiter=";")
df_superjunior = pd.read_csv("SuperJunior.csv", encoding="latin1", delimiter=";")


df_total = pd.concat([df_girls, df_shinee, df_superjunior], ignore_index=True)


df_total.head()